@hostname = http://localhost
@port = 5000
@host = {{hostname}}:{{port}}
@contentType = application/json
@http = HTTP/1.1


### update the profile of a user
POST {{host}}/api/account/komudi {{http}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtvbXVkaSIsInVzZXJJZCI6MiwiaWF0IjoxNzA2NjgwNTM4LCJleHAiOjE3MDcwNDA1Mzh9.WaDzrbxb4YBEBPCrHUrjwL6HhAxuadeMiyERULXmrNw 
Content-Type: {{contentType}}

{
    "username" : "komudi",
    "firstname": "Komudi",
    "lastname": "Gimhani",
    "location": "Meetiyagoda, Sri Lanka",
    "Bio": "I am a girl",
    "personalSite": "www.komudogimhani.lk"
}


### add user interests
POST {{host}}/api/account/shavin/interest {{http}}
Content-Type: {{contentType}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNoYXZpbiIsInVzZXJJZCI6MSwiaWF0IjoxNzE3MDAzMzc2LCJleHAiOjE3MTczNjMzNzZ9.Vz3nQ4wEcUS5xcitlJoKsqTYIg1oHd87J0ntYzKDFM4 

{
    "tags" : ["nature", "night"]
}

### get user download history
GET {{host}}/api/account/shavin/downloads {{http}}
Content-Type: {{contentType}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNoYXZpbiIsInVzZXJJZCI6MSwiaWF0IjoxNzEyOTQyMzgwLCJleHAiOjE3MTMzMDIzODB9.vz8EHh2_PY62nv2ted3LU0MrUWpOWCP0sRb2vQdiE1w

### delete a user account
DELETE {{host}}/api/account/omalyav {{http}}
Content-Type: {{contentType}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9tYWx5YXYiLCJ1c2VySWQiOjQsImlhdCI6MTcxNjI4NzUwOCwiZXhwIjoxNzE2NjQ3NTA4fQ.9lXbaqKBCrm8xbDIutgQhFXuHJ14D9SAbIwhmrkbb7I
