@hostname = http://localhost
@port = 5000
@host = {{hostname}}:{{port}}
@contentType = application/json
@http = HTTP/1.1

### Get the collections;
GET {{host}}/api/collections?sortBy=title&limit=2 {{http}}
Content-Type: {{contentType}}

### get the specific collection
GET {{host}}/api/collections/1 {{http}}
Content-Type: {{contentType}}

### get related collections 
GET {{host}}/api/collections/8/related {{http}}
Content-Type: {{contentType}}

### get the photos of the collection
GET {{host}}/api/collections/1/photo?limit=25 {{http}}
Content-Type: {{contentType}}

### new collection
POST {{host}}/api/collections {{http}}
Content-Type: {{contentType}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtvbXVkaSIsInVzZXJJZCI6MiwiaWF0IjoxNzA2NjgwNTM4LCJleHAiOjE3MDcwNDA1Mzh9.WaDzrbxb4YBEBPCrHUrjwL6HhAxuadeMiyERULXmrNw

{
    "title" : "Adventures",
    "description" : "Adventures in the world",
    "coverPhoto": 260,
    "photos": [260, 261, 262, 263, 264, 265, 266, 267, 268, 269]
}

### add photo to the collection
POST {{host}}/api/collections/13/ {{http}}
Content-Type: {{contentType}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNoYXZpbiIsInVzZXJJZCI6MSwiaWF0IjoxNzEyNjQ4Mjg0LCJleHAiOjE3MTMwMDgyODR9.YtbpQJHDEzKvsYJWZGLDlDhd0SGR971y61befG1ZhgM

{
    "photoIds": [360]
}


### get the tags of the collection
GET {{host}}/api/collections/1/tags {{http}}
Content-Type: {{contentType}}

### add new tags to the collection
POST {{host}}/api/collections/1/tags {{http}}
Content-Type: {{contentType}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNoYXZpbiIsInVzZXJJZCI6MSwiaWF0IjoxNzE3Mzk1NzE5LCJleHAiOjE3MTc3NTU3MTl9.5qxAhbs5lELoHjF2fjFc7NGFKJVnW7HdTD70NG_M1JA

{
    "tags": ["birds", "nature"]
}

### remove tags from the collection
POST {{host}}/api/collections/1/tags/remove {{http}}
Content-Type: {{contentType}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNoYXZpbiIsInVzZXJJZCI6MSwiaWF0IjoxNzE3Mzk1NzE5LCJleHAiOjE3MTc3NTU3MTl9.5qxAhbs5lELoHjF2fjFc7NGFKJVnW7HdTD70NG_M1JA

{
    "tags": ["birds"]

}

### update collection
PUT {{host}}/api/collections/4 {{http}}
Content-Type: {{contentType}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNoYXZpbiIsInVzZXJJZCI6MSwiaWF0IjoxNzE2Mjg2NzE2LCJleHAiOjE3MTY2NDY3MTZ9.O5jEkgUmxCoTCBF4_4nCWYIMakyCDUxMyW1akJHPLPM

{
    "collectionName": "Tasty Teas"
}

### delete a collection 
DELETE {{host}}/api/collections/4 {{http}}
Content-Type: {{contentType}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNoYXZpbiIsInVzZXJJZCI6MSwiaWF0IjoxNzE2Mjg2NzE2LCJleHAiOjE3MTY2NDY3MTZ9.O5jEkgUmxCoTCBF4_4nCWYIMakyCDUxMyW1akJHPLPM