@hostname = http://localhost
@port = 5000
@host = {{hostname}}:{{port}}
@contentType = application/json
@http = HTTP/1.1

### post new comment
POST {{host}}/api/photos/comment/25 {{http}}
Content-Type: {{contentType}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNoYXZpbiIsInVzZXJJZCI6MSwiaWF0IjoxNzE3OTQ3MDc0LCJleHAiOjE3MTgzMDcwNzR9.gM6ZBdebWA1RUS9vDZQVrBC5clAPvDIBsN1oXyC4LhY

{
    "comment": "This is a test comment 5"
}

### get all comments related to photo
GET {{host}}/api/photos/comment/20 {{http}}
Content-Type: {{contentType}}

### update a given document
PUT {{host}}/api/photos/comment/1 {{http}}
Content-Type: {{contentType}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNoYXZpbiIsInVzZXJJZCI6MSwiaWF0IjoxNzE3OTQ3MDc0LCJleHAiOjE3MTgzMDcwNzR9.gM6ZBdebWA1RUS9vDZQVrBC5clAPvDIBsN1oXyC4LhY
 
{
    "comment" : "This is a test comment 2 updated"
}

### delete a given comment
DELETE {{host}}/api/photos/comment/1 {{http}}
Content-Type: {{contentType}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNoYXZpbiIsInVzZXJJZCI6MSwiaWF0IjoxNzE3OTQ3MDc0LCJleHAiOjE3MTgzMDcwNzR9.gM6ZBdebWA1RUS9vDZQVrBC5clAPvDIBsN1oXyC4LhY
