@hostname = http://localhost
@port = 5000
@host = {{hostname}}:{{port}}
@contentType = application/json
@http = HTTP/1.1

GET {{host}}/api/photos?limit=12&page=1 {{http}}
Content-Type: {{contentType}}

### get photo by its id
@photoId = 9
GET {{host}}/api/photos/{{photoId}} {{http}}
Content-Type: {{contentType}}


### like a photo
@likedphotoId = 310
POST {{host}}/api/photos/{{likedphotoId}}/like {{http}}
Content-Type: {{contentType}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtvbXVkaSIsInVzZXJJZCI6MiwiaWF0IjoxNzA3NTg4MDE0LCJleHAiOjE3MDc5NDgwMTR9.4v4QE81P8w4iXF_yy3YZWop4aWgbqJ7tslnhAXnbMxI

{
    "rating" : 4
}

### dislike a photo
@dislikephotoId = 7
POST {{host}}/api/photos/{{dislikephotoId}}/dislike {{http}}
Content-Type: {{contentType}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNoYXZpbiIsInVzZXJJZCI6MSwiaWF0IjoxNzA0MTkxNjMzLCJleHAiOjE3MDQ1NTE2MzN9.4Uhbvp3PCz8FA641_zvJLXYHHiKKa5EpYAItzQu9Mjg


### download a photo
@downloadphotoId = 1
GET {{host}}/api/photos/{{downloadphotoId}}/download {{http}}
Content-Type: {{contentType}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNoYXZpbiIsInVzZXJJZCI6MSwiaWF0IjoxNzA0MTkxNjMzLCJleHAiOjE3MDQ1NTE2MzN9.4Uhbvp3PCz8FA641_zvJLXYHHiKKa5EpYAItzQu9Mjg


### download photo without a user
@downloadphotoId_ = 85
GET {{host}}/api/photos/{{downloadphotoId_}}/get {{http}}
Content-Type: {{contentType}}

### get stat about a photo
@statphotoId = 1
GET {{host}}/api/photos/{{statphotoId}}/statistics {{http}}
Content-Type: {{contentType}}


### get random photo
GET {{host}}/api/photos/random {{http}}
Content-Type: {{contentType}}

{
    "count": 4
}

### isl liked
@islikedphotoId = 250
GET {{host}}/api/photos/{{islikedphotoId}}/like {{http}}
Content-Type: {{contentType}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNoYXZpbiIsInVzZXJJZCI6MSwiaWF0IjoxNzA3NTg3OTYyLCJleHAiOjE3MDc5NDc5NjJ9._yKRsLyJf6zJ9x2IpVDMVzP-09HS55h2Dszlyt-9HZw


### get user likes
@userlikeId = 1
@userToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtvbXVkaSIsInVzZXJJZCI6MiwiaWF0IjoxNzExOTA2ODYwLCJleHAiOjE3MTIyNjY4NjB9.BQ-X2YBhx3-OmUBnsNRKLhPEnWZqYtb4y9h_SbF49qI
GET {{host}}/api/photos/likes {{http}}
Content-Type: {{contentType}}
Authorization: {{userToken}}

{
    "photoIds": [250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260]
}