@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json
@http = HTTP/1.1

GET {{host}}/api/photos {{http}}
Content-Type: {{contentType}}

{
    "page": 1,
    "limit": 3,
    "orderBy": "oldest"
}

### get photo ny its id
@photoId = 5
GET {{host}}/api/photos/{{photoId}} {{http}}
Content-Type: {{contentType}}


### like a photo
@likedphotoId = 7
POST {{host}}/api/photos/{{likedphotoId}}/like {{http}}
Content-Type: {{contentType}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNoYXZpbiIsInVzZXJJZCI6MSwiaWF0IjoxNzA0MTkxNjMzLCJleHAiOjE3MDQ1NTE2MzN9.4Uhbvp3PCz8FA641_zvJLXYHHiKKa5EpYAItzQu9Mjg

{
    "rating" : 3
}

### dislike a photo
@dislikephotoId = 7
POST {{host}}/api/photos/{{dislikephotoId}}/dislike {{http}}
Content-Type: {{contentType}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNoYXZpbiIsInVzZXJJZCI6MSwiaWF0IjoxNzA0MTkxNjMzLCJleHAiOjE3MDQ1NTE2MzN9.4Uhbvp3PCz8FA641_zvJLXYHHiKKa5EpYAItzQu9Mjg


### download a photo
@downloadphotoId = 1
GET {{host}}/api/photos/{{downloadphotoId}}/download {{http}}
Content-Type: {{contentType}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNoYXZpbiIsInVzZXJJZCI6MSwiaWF0IjoxNzA0MTkxNjMzLCJleHAiOjE3MDQ1NTE2MzN9.4Uhbvp3PCz8FA641_zvJLXYHHiKKa5EpYAItzQu9Mjg


### download photo without a user
@downloadphotoId_ = 1
GET {{host}}/api/photos/{{downloadphotoId_}}/get {{http}}
Content-Type: {{contentType}}

### get stat about a photo
@statphotoId = 1
GET {{host}}/api/photos/{{statphotoId}}/statistics {{http}}
Content-Type: {{contentType}}


### get random photo
GET {{host}}/api/photos/random {{http}}
Content-Type: {{contentType}}

{
    "count": 4
}