@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json
@http = HTTP/1.1

POST {{host}}/api/auth/register {{http}}
Content-Type: {{contentType}}

{
    "username": "shavin",
    "password": "shavin",
    "email": "shavin.anjitha@gmail.com",
    "firstname": "Shavin",
    "lastname": "Anjitha",
    "location": "Ambalangoda, Sri Lanka",
    "bio": "I am a undergradiate at University of Moratuwa."
}

###

POST {{host}}/api/auth/register {{http}}
Content-Type: {{contentType}}

{
    "username": "komudi",
    "password": "komudi",
    "email": "komudi.gimhani@gmail.com",
    "firstname": "Komudi",
    "lastname": "Gimhani",
    "location": "Meetiyagoda, Sri Lanka",
    "bio": "I am a model"
}

###


POST {{host}}/api/auth/register {{http}}
Content-Type: {{contentType}}

{
    "username": "supun",
    "password": "gimhan",
    "email": "supun.gimhan@gmail.com",
    "firstname": "Supun",
    "lastname": "Gimhan",
    "location": "Uragaha, Sri Lanka",
    "bio": "I am a engineering undergraduate."
}