@hostname = http://localhost
@port = 5000
@host = {{hostname}}:{{port}}
@contentType = application/json
@http = HTTP/1.1

### get users
GET {{host}}/api/users?limit=3 {{http}}

### get user by username
@username = shavin
GET {{host}}/api/users/{{username}} {{http}}

### get the photos by username
@username = komudi
GET {{host}}/api/users/{{username}}/photos {{http}}


### get the personal site of the user
@username = komudi
GET {{host}}/api/users/{{username}}/portfolio {{http}}

### get collection of users
GET {{host}}/api/users/shavin/collections {{http}}

### get the user liked photos
GET {{host}}/api/users/komudi/likes {{http}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtvbXVkaSIsInVzZXJJZCI6MiwiaWF0IjoxNzA3MDQzMTcxLCJleHAiOjE3MDc0MDMxNzF9.VTjBe3REhKzqObkbgyP9rvuE3I0fDGpCJ87oIX3j_ZA

### get the stat of a user
GET {{host}}/api/users/shavin/stat {{http}}

### follow a user
POST {{host}}/api/users/komudi/follow {{http}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNoYXZpbiIsInVzZXJJZCI6MSwiaWF0IjoxNzA2NjM1MDg4LCJleHAiOjE3MDY5OTUwODh9.g3d-V-jbHPtbvDVQSF1eZVtIStwfKx_DFnq8H4lRf84

### user interest of a user
GET {{host}}/api/users/shavin/interests {{http}}
Content-Type: {{contentType}}

